### ISSUE TITLE
Bug - Magento - Quantity Selector

### ISSUE THREAD

**Issue by FranklyLars** [franklyinsure/magento-extension#1]
**Description**
The placement of the buttons and the number in the quantity selector is off, also the color of both the buttons and the number is off as well.

**Steps**
1. Go to magento plugin.
2. Add multiple of an insurable product into the basket and head to checkout.
3. At the popup you will be able to see the above mentioned issues.

**Reference**
Related to wordpress issue: https://app.zenhub.com/workspaces/frankly-insure-6395f5c5d94c93fe5b856901/issues/gh/franklyinsure/wordpress-plugin/97

**Comment by stathmos** [comment]
When I open this, it says file permission denied. Can you share via whatsapp or any google drive link?

**Comment by FranklyChris** [comment]
It doesn't look terrible, but the numbers (quantity) are placed a bit high @mwFrankly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFdJQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c1c5394cc06a3db8e7edd58c4375338b02068d6/Screenshot%202023-10-31%20at%2011.25.47.png)

**Comment by FranklyChris** [comment]
Status: Test not passed.

**Comment by mwFrankly** [comment]
Closing this as design will be upgraded
