### ISSUE TITLE
Fix SQL Injection Vulnerability

### ISSUE THREAD

**Issue by Nurgiel** [franklyinsure/magento-extension#10]
vendor/frankly/insure/Block/Success.php:212

`$sql = "UPDATE $tableName SET frankly_insurance_number_failed = '".$frankly_insurance_number_failed."', frankly_insurance_mp_url = '". $frankly_insurance_mp_url ."', agreement_id = '". $agreement_id ."' WHERE order_id = '". $orderIncrementId ."'";`

A malicious threat actor can mock $orderIncrementId in the response to e.g. $orderIncrementId = "1' OR 1=1; DROP TABLE sales_order;"

How to fix?

Instead of concatenating strings in $sql you should prepare/sanitize the SQL Query properly:
```
$stmt = $connection->prepare("UPDATE $tableName SET frankly_insurance_number_failed = ?, frankly_insurance_mp_url = ?, agreement_id = ? WHERE order_id = ?");

// Bind the variables to the prepared statement
$stmt->bindParam(1, $frankly_insurance_number_failed);
$stmt->bindParam(2, $frankly_insurance_mp_url);
$stmt->bindParam(3, $agreement_id);
$stmt->bindParam(4, $orderIncrementId);

// Execute the statement
$stmt->execute();
```

**Comment by mwFrankly** [comment]
@Nurgiel thanks for the reported issue.

**Comment by stathmos** [comment]
This is fixed. Will release in next version.

**Comment by mwFrankly** [comment]
@stathmos as per the discussion, update with prepared statements

**Comment by mwFrankly** [comment]
verified and close
