### ISSUE TITLE
Bug - Magento - Uncaught TypeError: totalCoverage is undefined

### ISSUE THREAD

**Issue by FranklyLars** [franklyinsure/magento-extension#11]
**Description**
Unlike the wordpress plugin, this error seems contained to pages that actually use our javascript. The issue is that our javascript is running no matter what and a possible solution to this would be to wrap a condition around it, to make sure it only runs when needed.

**Steps**
1. Go to the magento plugin.
2. Add any **uninsurable** product to the cart and head to checkout.
3. Check the console for the error message.

**Comment by stathmos** [comment]
Yes, this is also done. Will be pushed in next release.

**Comment by FranklyChris** [comment]
Status: This test has passed!
