### ISSUE TITLE
Fix issues reported by distributor

### ISSUE THREAD

**Issue by mwFrankly** [franklyinsure/magento-extension#12]
Objectmanager is used. Bad practice.

Lots of commented code leftovers from previous iterations.

Install/setup uses deprecated functionality

CSS errors breaking other styles

Hardcoded strings that can't be translated

Hardcoded order id 4 in a file?

Menu should be placed as a child in Sales to not bloat the main menu.

**Comment by stathmos** [comment]
These issues are done. Will be in next release.

**Comment by mwFrankly** [comment]
fixing a issue in new installation changes

**Comment by mwFrankly** [comment]
verified
