### ISSUE TITLE
cURL requests should use https 

### ISSUE THREAD

**Issue by mwFrankly** [franklyinsure/magento-extension#14]
Current curl calls are not using encrypted layer of http for data transfer

**Comment by mwFrankly** [comment]
Update below values for production to make secure connection to server
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 2);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 1);

**Comment by stathmos** [comment]
Hello, yes this was already done yesterday.

You will see once I push the latest code.

**Comment by mwFrankly** [comment]
ok thank you

**Comment by mwFrankly** [comment]
This is tested on testing env

**Comment by mwFrankly** [comment]
verified
