### ISSUE TITLE
Remove the unwanted elements from request

### ISSUE THREAD

**Issue by mwFrankly** [franklyinsure/magento-extension#15]
remove below from frankly/insure/Block/Success.php file line 78 since this is not required for now
"ssn" => "123123", // TODO: require to find out how to capture product serial number

**Comment by stathmos** [comment]
With product serial number, do you mean product SKU?

**Comment by mwFrankly** [comment]
$customer_data = [
	         
	            "ssn" => "123123", // TODO: require to find out how to capture product serial number
	            
	        ];
	        
	        in here under customer data

**Comment by stathmos** [comment]
It's commented now.

**Comment by mwFrankly** [comment]
Status: this is completed
