### ISSUE TITLE
Disable extension based on region 

### ISSUE THREAD

**Issue by mwFrankly** [franklyinsure/magento-extension#16]
User shoudnt see the popup if located outside Denmark

**Comment by stathmos** [comment]
We can use this service : https://ipgeolocation.io/pricing.html

30k requests are free per month.

Can you sign up here and share you account details?

**Comment by mwFrankly** [comment]
Hi @stathmos 
Please check the domain name of the wesbiste and if its on https://sharkgaming.dk/ then show the popup , if its https://sharkgaming.se/ or https://sharkgaming.no/ popup is not required

**Comment by stathmos** [comment]
Hi @mwFrankly , we have made the scope from Global to Website. I assume that you have multi-website concept in your same magento instance. So you can enable/disable based on website from admin itself. Please let me know if this is fine.

**Comment by mwFrankly** [comment]
@stathmos not sure how they manage it , we will check with Distributor tomrw. I believe the once you suggested is good with us

**Comment by mwFrankly** [comment]
https://magentotesting.franklyinsure.com

**Comment by mwFrankly** [comment]
Status: this is completed, can be disabled baed on website scope
