### ISSUE TITLE
Bug - Magento - Plus signs on popup info page

### ISSUE THREAD

**Issue by FranklyLars** [franklyinsure/magento-extension#2]
**Description**
The plus signs on the popup info page in the first info card have the wrong color, they are grey but should be black.

**Steps**
1. Go to the magento plugin.
2. Add any insurable product to the cart and proceed to checkout.
3. At the popup, press the info button in the lower right corner to get to the info page.
4. At the info page, view the above mentioned issues in the first info card.

**Reference**
Related to Wordpress issue https://app.zenhub.com/workspaces/frankly-insure-6395f5c5d94c93fe5b856901/issues/gh/franklyinsure/wordpress-plugin/94

**Comment by stathmos** [comment]
This is done.

**Comment by mwFrankly** [comment]
Closing due to design will be replaced with new design
