### ISSUE TITLE
Bug - Magento | Console error regarding loading of Spartan font

### ISSUE THREAD

**Issue by FranklyChris** [franklyinsure/magento-extension#20]
Steps to reproduce:

1. Go to magentotesting site.
2. Add any product to basket.
3. Proceed to checkout
4. View the error(s) in the console regarding the font.

<img width="1490" alt="Screenshot 2023-10-31 at 13 58 37" src="https://github.com/franklyinsure/magento-extension/assets/122975902/834df338-275a-47b2-a0d5-efc813068415">

**Comment by mwFrankly** [comment]
@stathmos can you help check is this coming from our extension. ?

**Comment by stathmos** [comment]
This is done.

**Comment by mwFrankly** [comment]
verified
