### ISSUE TITLE
Selected products are not visible on Checkout page

### ISSUE THREAD

**Issue by mwFrankly** [franklyinsure/magento-extension#26]
Find the screenshot for reference.
![SCR-20231108-sbcr](https://github.com/franklyinsure/magento-extension/assets/134401968/9d680854-39eb-4c95-80d2-3d522fafca3e)

**Comment by FranklyChris** [comment]
Status: Tested on magentotesting, it works.
As you can see I have two products and two insurance products in the cart. 
<img width="407" alt="Screenshot 2023-11-14 at 10 50 18" src="https://github.com/franklyinsure/magento-extension/assets/122975902/4091b9e6-af2c-41b0-b383-6b870f59c13c">

**Comment by mwFrankly** [comment]
this is closing due to design change
