### ISSUE TITLE
Overlay does not cover entire page

### ISSUE THREAD

**Issue by mwFrankly** [franklyinsure/magento-extension#27]
find the screenshot below.
![SCR-20231108-shtl](https://github.com/franklyinsure/magento-extension/assets/134401968/432af9f1-6de3-424c-ace1-2d1a81599773)

**Comment by FranklyChris** [comment]
Status: Tested on magentotesting, it worsk.
<img width="1680" alt="Screenshot 2023-11-14 at 10 27 59" src="https://github.com/franklyinsure/magento-extension/assets/122975902/716a7386-79d6-470d-9470-b2b9c71a2b92">
