### ISSUE TITLE
Bug - Magento - Scrollbar in Chrome and Edge

### ISSUE THREAD

**Issue by FranklyLars** [franklyinsure/magento-extension#3]
**Description**
The scrollbar is off in chrome and edge, most likely also safari, but that has not been confirmed. See images for how it looks and how it should look.

**Steps**
1. Go to magento plugin in either chrome or edge.
2. Add multiple insurable products to the cart, as many as you can and head to checkout.
3. If the scrollbar isnt visible, you can resize the window to make the scrollbar pop.
4. Examine the scrollbar.

**Reference**
Related to wordpress issue: https://app.zenhub.com/workspaces/frankly-insure-6395f5c5d94c93fe5b856901/issues/gh/franklyinsure/wordpress-plugin/92

**Images**
Chrome:
![image](https://github.com/franklyinsure/magento-extension/assets/98809354/10ef2fd0-957e-4c60-a14f-2cdd2aab6967)

Edge:
![image](https://github.com/franklyinsure/magento-extension/assets/98809354/db8abbde-eafc-42f3-810b-22ca96334ff5)

Firefox **(how it should look)**:
![image](https://github.com/franklyinsure/magento-extension/assets/98809354/6d6b5a7b-ccfd-4d80-9055-e4dd70b63d66)

**Comment by stathmos** [comment]
This is done.

**Comment by mwFrankly** [comment]
Closing due to design will be replaced with new design
