### ISSUE TITLE
Bug - Magento - Slider checkmark

### ISSUE THREAD

**Issue by FranklyLars** [franklyinsure/magento-extension#4]
**Description**
The slider checkmark is missing.

**Steps**
1. Go to the magento plugin.
2. Add any insurable product to the cart and head to checkout.
3. In the popup add an insurance to the cart and see if the checkmark is there in the slider.

**Images**
How it looks:
![image](https://github.com/franklyinsure/magento-extension/assets/98809354/04d1ad0c-13c8-4fd2-b05a-51542af41059)

How it should look:
![image](https://github.com/franklyinsure/magento-extension/assets/98809354/83b7b2a1-e367-4218-9497-912fe4218ac7)

**Comment by stathmos** [comment]
It's done
![image](https://github.com/franklyinsure/magento-extension/assets/69260507/798c527f-03ee-4162-b98c-aa67433e30a5)

**Comment by FranklyChris** [comment]
Status: Tested and it works on magentotesting site.
