### ISSUE TITLE
Bug - Magento  - Quantity selector decimal number

### ISSUE THREAD

**Issue by FranklyLars** [franklyinsure/magento-extension#44]
**Description**
The quantity selector starts with decimal numbers, but corrects itself once you change the quantity. This is caused by shark gaming supplying the quantity in decimal numbers. If this is intended behavior on shark gamings side is unknown, but if it is, its just a matter of cleansing the input before typing it out, if we wish to divert from shark gamings behavior.

**Comment by mwFrankly** [comment]
Status: this is completed
