### ISSUE TITLE
Bug - Magento - "F" in logo is off center

### ISSUE THREAD

**Issue by FranklyLars** [franklyinsure/magento-extension#6]
**Description**
As the title says the "F" in the popup logo is off-center

**Steps**
1. Go to the magento plugin
2. At the popup, you can see the "F" in the logo is off center.

**Images**
How it looks:
![image](https://github.com/franklyinsure/magento-extension/assets/98809354/fc3bae58-dea5-40fa-adab-1b1dfaf2f0b1)

How it should look:
![image](https://github.com/franklyinsure/magento-extension/assets/98809354/8eb96237-5001-4411-b875-f4e427b85455)

**Comment by stathmos** [comment]
This is done.

**Comment by mwFrankly** [comment]
Closing due to design will be replaced with new design
