### ISSUE TITLE
Popup Background blur issue  on Chrome & Edge 

### ISSUE THREAD

**Issue by mwFrankly** [franklyinsure/magento-extension#62]
<img width="1217" alt="SCR-20231118-szhb" src="https://github.com/franklyinsure/magento-extension/assets/134401968/43df45a9-f297-4f0e-8725-819273950e34">

**Comment by nicolaiarnholm** [comment]
Update: Tried on Safari, Chrome, Edge and Firefox. Issue is also present on Microsoft Edge 

Chrome
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2pwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1aae74fb74f48148095f6a43247fc226e7a72a85/Chrome.png)

Firefox
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3JwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--21ee1f12347a22f42b08227b6edd8fdba8fd85df/Firefox.png)

Safari
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3ZwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94347238db24802e09121f465dc3a711ed69fa12/Safari.png)

Edge
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3pwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2bea29667232c6192bcf00b7abd61b9f6585bf30/Edge.png)

**Comment by nicolaiarnholm** [comment]
Tested and works

**Comment by mwFrankly** [comment]
Status: this is completed
