### ISSUE TITLE
Bug - Magento - Expanded insurance product checkmarks are off

### ISSUE THREAD

**Issue by FranklyLars** [franklyinsure/magento-extension#7]
**Description**
The checkmarks when an insurance product is expanded are off. This is both the case on Magento & wordpress and there will be an issue for the wordpress version. It looks like there is a fill #000 there shouldnt be.

**Steps**
1. Go to the magento plugin
2. Head to the popup and inspect the checkmarks on the expanded product.

**Images**
How it looks:
![image](https://github.com/franklyinsure/magento-extension/assets/98809354/01a6bbbe-58ee-4269-9348-57fec0ce3e53)

How it should look:
![image](https://github.com/franklyinsure/magento-extension/assets/98809354/74c43e43-c658-4e3c-a66e-79f312e34e0d)

**Figma**
[Figma Master design](https://www.figma.com/file/q73RprRSFss6sQNwnBMP2X/Master-Design-File?type=design&node-id=1188-13264&mode=design&t=lfwmZtfhh22HIXHC-0)

**Reference**
Wordpress issue:
https://app.zenhub.com/workspaces/frankly-insure-6395f5c5d94c93fe5b856901/issues/gh/franklyinsure/wordpress-plugin/109

**Comment by mwFrankly** [comment]
Closing due to design will be replaced with new design
