### ISSUE TITLE
Bug - Magento - Quantity added twice to insurance products in cart

### ISSUE THREAD

**Issue by FranklyLars** [franklyinsure/magento-extension#8]
**Description**
There is an " x 2" or what ever you quantity is, following the insurance product in the cart, which is much like how our wordpress plugin works, but on magento we have a separate quantity and therefor the quantity statement in the product name is superflous.

**Steps**
1. Go to the magento plugin.
2. Add multiple of an insurable product to the cart and head to checkout.
3. Add multiple of an insurance product to the cart and place order.
4. At the Order Summary you can see the above mentioned issue.

**Images**
How it looks:
![image](https://github.com/franklyinsure/magento-extension/assets/98809354/dca7ad05-3000-49d9-b05d-0cefaf19263a)

**Comment by stathmos** [comment]
As per discussion, will work on this later.

**Comment by mwFrankly** [comment]
closing since not relevant with new design
