### ISSUE TITLE
Bug - Magento - Order Summary item count doesnt match

### ISSUE THREAD

**Issue by FranklyLars** [franklyinsure/magento-extension#9]
**Description**
In the Order Summary after you have added the insurances to the cart and placed the order, the "Items in Cart" count is not counting the insurances and therefor is off.

**Steps**
1. Go to the magento plugin.
2. Add an insurable product to the cart and head to checkout.
3. At the popup add an insurance to the cart and place order.
4. At the Order Summary you can see the "Items in Cart" count matches only the products you purchased and not the insurance products.

**Images**
How it looks:
![image](https://github.com/franklyinsure/magento-extension/assets/98809354/de2568a7-a0eb-453a-8a52-712caa14ffba)

**Comment by mwFrankly** [comment]
@FranklyLars this is not an issue since there is only one product in cart.
